import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { api, can } from '../api.js'
import { EmptyState, ErrorState, PageSkeleton, PermissionHint, Spinner } from '../components/States.jsx'
import { navigate } from '../router.jsx'

const FILTERS = ['all', 'critical', 'high', 'medium', 'low']

export default function AlertsPage({ role }) {
  const [alerts, setAlerts] = useState(null)
  const [filter, setFilter] = useState('all')
  const [status, setStatus] = useState('open')
  const [query, setQuery] = useState('')
  const [screening, setScreening] = useState(false)
  const [notice, setNotice] = useState(null)
  const [error, setError] = useState(null)
  const timeout = useRef(null)

  const load = useCallback(() => {
    setError(null)
    api('/api/alerts', { role }).then((d) => setAlerts(d.alerts ?? d ?? [])).catch(setError)
  }, [role])
  useEffect(load, [load])
  useEffect(() => () => clearTimeout(timeout.current), [])

  const runScreening = async () => {
    setScreening(true)
    setNotice(null)
    try {
      const result = await api('/api/screening/run', { method: 'POST', role })
      setAlerts(result.alerts ?? [])
      setNotice(`${result.transactions_scanned?.toLocaleString() ?? 'All'} transactions evaluated · ${(result.alerts ?? []).length} signals raised`)
      timeout.current = setTimeout(() => setNotice(null), 5000)
    } catch (e) { setError(e) } finally { setScreening(false) }
  }

  const filtered = useMemo(() => (alerts ?? []).filter((item) => {
    const matchSeverity = filter === 'all' || item.severity === filter
    const matchStatus = status === 'all' || (item.status ?? 'open') === status
    const haystack = `${item.id} ${item.customer_name} ${item.rule} ${item.summary}`.toLowerCase()
    return matchSeverity && matchStatus && haystack.includes(query.toLowerCase())
  }), [alerts, filter, status, query])

  if (error && !alerts) return <ErrorState error={error} retry={load} />
  if (!alerts) return <PageSkeleton rows={4} />
  const screenAllowed = can(role, 'screen')

  return (
    <div className="page alerts-page">
      <header className="page-head">
        <div><div className="eyebrow">Deterministic monitoring</div><h1>Alert queue</h1><p>Prioritized signals generated by explainable detection rules.</p></div>
        <button className="btn primary" onClick={runScreening} disabled={screening || !screenAllowed} title={!screenAllowed ? 'Available to the AML Analyst persona' : undefined}>
          {screening ? <Spinner label="Screening" /> : 'Run screening'}
        </button>
      </header>
      {!screenAllowed && <PermissionHint>Screening is analyst-controlled. Switch to the <strong>AML Analyst</strong> persona to run the rule set.</PermissionHint>}
      {notice && <div className="success-toast" role="status"><span>✓</span>{notice}</div>}

      <section className="surface queue-surface">
        <div className="toolbar">
          <label className="search-field"><span aria-hidden="true">⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customer, alert, or rule" aria-label="Search alerts" /></label>
          <div className="filter-tabs" role="group" aria-label="Filter by severity">
            {FILTERS.map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}
          </div>
          <label className="select-field"><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="open">Open</option><option value="all">All</option><option value="investigating">Investigating</option><option value="sar_draft">SAR draft</option><option value="pending_review">Pending review</option><option value="sar_approved">SAR approved</option><option value="closed_no_sar">Closed</option></select></label>
        </div>

        {filtered.length ? (
          <div className="data-table alert-table" aria-label="Alerts">
            <div className="table-head"><span>Severity</span><span>Customer & signal</span><span>Rule</span><span>Raised</span><span>Status</span><span /></div>
            {filtered.map((alert) => (
              <button className="table-row" key={alert.id} onClick={() => navigate(`/cases/${alert.id}`)}>
                <span><span className={`severity-label ${alert.severity}`}><i />{alert.severity}</span></span>
                <span><strong>{alert.customer_name}</strong><small>{alert.id} · {alert.summary}</small></span>
                <span className="mono">{alert.rule}</span>
                <span>{String(alert.created ?? '—').slice(0, 10)}</span>
                <span><span className={`status-label ${alert.status ?? 'open'}`}>{String(alert.status ?? 'open').replaceAll('_', ' ')}</span></span>
                <span className="row-arrow">→</span>
              </button>
            ))}
          </div>
        ) : (
          <EmptyState title="No alerts match this view" body="Adjust the severity, status, or search filters to widen the queue." />
        )}
      </section>
    </div>
  )
}
