"""
Raqib — SAR PDF export (English + Arabic).

One canvas-based renderer, two languages. Arabic strings go through
arabic_reshaper + bidi (the house ReportLab pattern) and render in Noto
Naskh, right-aligned; numbers and entity names stay Latin. The Arabic
narrative itself comes from the SAR's structured `narrative_ar` field —
generated in the same responses.parse call as the English one.
"""

from __future__ import annotations

import io
from datetime import date

import arabic_reshaper
from bidi.algorithm import get_display
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

import config

INK = HexColor("#181818")
MUTED = HexColor("#6b6960")
ACCENT = HexColor("#bd5d3a")
PAPER = HexColor("#f5f0e8")
RULE = HexColor("#d6cbb8")
CRIMSON = HexColor("#9c3d2e")

W, H = A4
MARGIN = 52

L = {  # static labels per language
    "en": {"title": "Suspicious Activity Report", "subject": "Subject", "pattern": "Pattern",
           "period": "Period", "total": "Total flows", "risk": "Risk score",
           "findings": "Key findings", "cps": "Counterparties", "narrative": "Narrative",
           "actions": "Recommended actions", "policy": "Policy sections engaged",
           "filing": "SAR filing required", "no_filing": "No SAR filing required",
           "footer": "Generated by Raqib on OCI Enterprise AI — fictional demo data"},
    "ar": {"title": "تقرير نشاط مشبوه", "subject": "الطرف المعني", "pattern": "النمط",
           "period": "الفترة", "total": "إجمالي التدفقات", "risk": "درجة الخطورة",
           "findings": "أبرز النتائج", "cps": "الأطراف المقابلة", "narrative": "الوقائع",
           "actions": "الإجراءات الموصى بها", "policy": "بنود السياسة المعنية",
           "filing": "يتوجب رفع تقرير نشاط مشبوه", "no_filing": "لا يلزم رفع تقرير",
           "footer": "صادر عن رقيب — بيانات تجريبية لأغراض العرض"},
}


def _register_fonts():
    if "NotoNaskh" not in pdfmetrics.getRegisteredFontNames():
        pdfmetrics.registerFont(TTFont("NotoNaskh", str(config.PROJECT_ROOT / "NotoNaskhArabic-Regular.ttf")))


def _ar(text: str) -> str:
    return get_display(arabic_reshaper.reshape(text))


def _wrap(c, text: str, font: str, size: float, max_w: float, rtl=False) -> list[str]:
    """Wrap LOGICAL text into lines, then bidi-shape each line for display.

    Order matters: shaping the whole paragraph first and wrapping the visual
    string renders RTL paragraphs bottom-up. Line measurement uses the shaped
    form so ligature widths are correct.
    """
    shaped = (lambda t: _ar(t)) if rtl else (lambda t: t)
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = f"{cur} {w}".strip()
        if c.stringWidth(shaped(trial), font, size) <= max_w:
            cur = trial
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return [shaped(line) for line in lines]


class Sheet:
    """Tiny layout helper: tracks the cursor, draws LTR or RTL consistently."""

    def __init__(self, c: canvas.Canvas, rtl: bool):
        self.c, self.rtl, self.y = c, rtl, H - MARGIN
        self.body_font = "NotoNaskh" if rtl else "Helvetica"
        self.head_font = "NotoNaskh" if rtl else "Times-Bold"

    def t(self, s: str) -> str:
        return _ar(s) if self.rtl else s

    def text(self, s: str, size=9.5, font=None, color=INK, leading=None, indent=0):
        font = font or self.body_font
        for line in _wrap(self.c, s, font, size, W - 2 * MARGIN - indent, rtl=self.rtl):
            self.need(size + 6)
            self.c.setFont(font, size)
            self.c.setFillColor(color)
            if self.rtl:
                self.c.drawRightString(W - MARGIN - indent, self.y, line)
            else:
                self.c.drawString(MARGIN + indent, self.y, line)
            self.y -= (leading or size * 1.5)

    def heading(self, s: str):
        self.y -= 12
        self.need(30)
        self.c.setFillColor(ACCENT)
        self.c.setFont(self.head_font, 11.5)
        if self.rtl:
            self.c.drawRightString(W - MARGIN, self.y, self.t(s))
        else:
            self.c.drawString(MARGIN, self.y, self.t(s))
        self.y -= 7
        self.c.setStrokeColor(RULE)
        self.c.setLineWidth(0.7)
        self.c.line(MARGIN, self.y, W - MARGIN, self.y)
        self.y -= 14

    def need(self, room: float):
        if self.y - room < MARGIN + 20:
            self.c.showPage()
            self.y = H - MARGIN


def build_pdf(sar: dict, lang: str = "en") -> bytes:
    _register_fonts()
    rtl = lang == "ar"
    lab = L["ar" if rtl else "en"]
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    s = Sheet(c, rtl)

    # Masthead
    c.setFillColor(PAPER)
    c.rect(0, H - 108, W, 108, stroke=0, fill=1)
    c.setFillColor(INK)
    c.setFont("Times-Bold" if not rtl else "NotoNaskh", 21)
    title_y = H - 58
    if rtl:
        c.drawRightString(W - MARGIN, title_y, _ar(lab["title"]))
        c.setFont("Helvetica", 9)
        c.setFillColor(MUTED)
        c.drawString(MARGIN, title_y, f"Raqib · {sar['case_id']} · {date.today().isoformat()}")
    else:
        c.drawString(MARGIN, title_y, lab["title"])
        c.setFont("Helvetica", 9)
        c.setFillColor(MUTED)
        c.drawRightString(W - MARGIN, title_y, f"Raqib · {sar['case_id']} · {date.today().isoformat()}")
    c.setFillColor(ACCENT)
    filing = lab["filing"] if sar["sar_filing_required"] else lab["no_filing"]
    if rtl:
        # Arabic labels must render in NotoNaskh — Helvetica has no Arabic glyphs.
        c.setFont("NotoNaskh", 10)
        c.drawRightString(W - MARGIN, H - 84,
                          _ar(f"{lab['risk']}: {sar['risk_score']}/100 · {sar['risk_level'].upper()}"))
        c.setFillColor(CRIMSON if sar["sar_filing_required"] else MUTED)
        c.drawString(MARGIN, H - 84, _ar(filing))
    else:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(MARGIN, H - 84, f"{lab['risk']}: {sar['risk_score']}/100 · {sar['risk_level'].upper()}")
        c.setFillColor(CRIMSON if sar["sar_filing_required"] else MUTED)
        c.drawRightString(W - MARGIN, H - 84, filing)
    s.y = H - 136

    # Header facts
    s.text(f"{lab['subject']}: {sar['subject']}", size=11, font=s.head_font)
    s.text(f"{lab['pattern']}: {sar['pattern_type']}")
    period = sar["period"].replace(" to ", " إلى ") if rtl else sar["period"]
    s.text(f"{lab['period']}: {period}   ·   {lab['total']}: AED {sar['total_amount_aed']:,.0f}")

    s.heading(lab["findings"])
    for i, f in enumerate(sar["key_findings"], 1):
        s.text(f"{i}.  {f}", indent=6)

    s.heading(lab["cps"])
    for cp in sar["counterparties"]:
        hit = " — WATCHLIST HIT" if cp["watchlist_hit"] else ""
        s.text(f"{cp['name']} ({cp['country']}) · AED {cp['total_aed']:,.0f}{hit}",
               color=CRIMSON if cp["watchlist_hit"] else INK, indent=6)
        if cp.get("note"):
            s.text(cp["note"], size=8.5, color=MUTED, indent=18)

    s.heading(lab["policy"])
    s.text(" · ".join(sar["policy_sections_engaged"]))

    s.heading(lab["narrative"])
    s.text(sar["narrative_ar"] if rtl else sar["narrative"], size=10, leading=17)

    s.heading(lab["actions"])
    for a in sar["recommended_actions"]:
        s.text(f"—  {a}", indent=6)

    c.setFont("NotoNaskh" if rtl else "Helvetica", 7.5)
    c.setFillColor(MUTED)
    c.drawCentredString(W / 2, 30, _ar(lab["footer"]) if rtl else lab["footer"])
    c.save()
    return buf.getvalue()
