"""
Raqib — Pydantic schemas.

SARReport is the structured deliverable of an investigation: generated by
`responses.parse` (JSON-schema mode, no regex extraction) and consumed by the
UI panel and the EN/AR PDF export.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Counterparty(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    name: str = Field(min_length=1)
    country: str = Field(min_length=1)
    total_aed: float = Field(ge=0, allow_inf_nan=False)
    watchlist_hit: bool
    note: str = ""


class SARReport(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    case_id: str = Field(min_length=1)
    subject: str = Field(min_length=1, description="Customer legal name")
    risk_level: Literal["low", "medium", "high", "critical"]
    risk_score: int = Field(ge=0, le=100, strict=True)
    pattern_type: str = Field(min_length=1, description="e.g. 'Structuring followed by rapid layering'")
    period: str = Field(min_length=1, description="e.g. '2026-06-08 to 2026-06-19'")
    total_amount_aed: float = Field(ge=0, allow_inf_nan=False)
    counterparties: list[Counterparty]
    policy_sections_engaged: list[str] = Field(description="e.g. ['§4.2 Structuring']")
    key_findings: list[str]
    narrative: str = Field(min_length=1, description="Formal SAR narrative, 150-250 words, third person")
    narrative_ar: str = Field(min_length=1, description="The same narrative in formal Arabic (فصحى), for the Arabic filing copy")
    recommended_actions: list[str]
    sar_filing_required: bool


Role = Literal["analyst", "reviewer", "auditor", "rule_admin"]


class NoteCreate(BaseModel):
    text: str = Field(min_length=1, max_length=2000)


class CaseTransition(BaseModel):
    status: Literal[
        "open", "investigating", "draft_ready", "pending_review",
        "approved", "changes_requested", "closed",
    ]
    reason: str | None = Field(default=None, max_length=500)


class RuleUpdate(BaseModel):
    enabled: bool | None = None
    parameters: dict[str, Any] | None = None


class RuleSimulation(BaseModel):
    parameters: dict[str, Any] | None = None


class SARReview(BaseModel):
    decision: Literal["approved", "changes_requested"]
    comment: str | None = Field(default=None, max_length=1000)


class ApprovalDecision(BaseModel):
    """Out-of-band SQL-approval decision (reconnect-safe). The call_id binds the
    decision to the pending query, exactly like the WebSocket path."""
    approve: bool
    call_id: str | None = None


class BulkTriage(BaseModel):
    """One triage action applied across many cases from the queue."""
    case_ids: list[str] = Field(min_length=1, max_length=200)
    action: Literal["assign", "priority", "transition"]
    owner: str | None = Field(default=None, max_length=120)
    priority: Literal["urgent", "high", "medium", "low"] | None = None
    status: Literal[
        "open", "investigating", "draft_ready", "pending_review",
        "approved", "changes_requested", "closed",
    ] | None = None
    reason: str | None = Field(default=None, max_length=500)


def ev(type_: str, **kw) -> dict:
    """One WebSocket event. The UI switches on `type`."""
    return {"type": type_, **kw}
